version: '3.8'

volumes:
  database:

services:
  postgres:
    image: postgres:15
    container_name: kodemo_db
    restart: unless-stopped
    ports:
      - 54320:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-kodemo}
      - POSTGRES_USER=${POSTGRES_USER:-kodemo}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-kodemo}
    volumes:
      - database:/var/lib/postgresql/data

  pgweb:
    container_name: pgweb
    restart: always
    image: sosedoff/pgweb
    ports:
      - 8081:8081
